CREATE TABLE tags (
    tag_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tag_name VARCHAR(255) NOT NULL,
    tag_description TEXT
);

CREATE UNIQUE INDEX "lowered_tag_name" ON tags ((LOWER(tag_name)));

CREATE TABLE objects (
    object_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    object_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    object_name VARCHAR(255) NOT NULL,
    object_description TEXT
);

CREATE INDEX "object_type_index" ON objects (object_type);
CREATE UNIQUE INDEX "lowered_object_name" ON objects ((LOWER(object_name)));

CREATE TABLE objects_tags (
    tag_id INT NOT NULL REFERENCES tags(tag_id),
    object_id INT NOT NULL REFERENCES objects(object_id)
);

CREATE UNIQUE INDEX "objects_tags_index" ON objects_tags (object_id, tag_id);

CREATE TABLE links (
    object_id INT UNIQUE NOT NULL REFERENCES objects(object_id),
    link TEXT NOT NULL
);

CREATE TABLE markdown (
    object_id INT UNIQUE NOT NULL REFERENCES objects(object_id),
    raw_text TEXT NOT NULL
);

CREATE TABLE to_do_lists (
    object_id INT UNIQUE NOT NULL REFERENCES objects(object_id),
    sort_type VARCHAR(32) NOT NULL
);

CREATE TABLE to_do_list_items (
    object_id INT NOT NULL REFERENCES to_do_lists(object_id),
    item_number INT NOT NULL,
    item_state VARCHAR(32) NOT NULL,
    item_text TEXT,
    commentary TEXT,
    indent INT NOT NULL,
    is_expanded BOOLEAN NOT NULL
)
