""" "Tags is_published"

Revision ID: 7c8e91045b4d
Revises: e66848bfd877
Create Date: 2022-09-15 21:59:54.519123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8e91045b4d'
down_revision = 'e66848bfd877'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('tags', sa.Column('is_published', sa.Boolean()))
    op.execute("UPDATE tags SET is_published=TRUE")
    op.alter_column('tags', 'is_published', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_published')
    # ### end Alembic commands ###
