""" "Composite objects"

Revision ID: 7f3a49a733c7
Revises: 987f81c7b064
Create Date: 2021-05-02 12:43:30.470132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3a49a733c7'
down_revision = '987f81c7b064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('subobject_id', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('selected_tab', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['public.objects.object_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subobject_id'], ['public.objects.object_id'], ondelete='CASCADE'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composite', schema='public')
    # ### end Alembic commands ###
