""" "test 2"

Revision ID: 91928f159ec7
Revises: e66848bfd877
Create Date: 2022-05-29 15:05:02.946517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91928f159ec7'
down_revision = 'e66848bfd877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
