""" "Public settings"

Revision ID: 9e5329392687
Revises: 4c0477896c90
Create Date: 2021-10-10 16:18:44.536369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5329392687'
down_revision = '4c0477896c90'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('settings', sa.Column('is_public', sa.Boolean()))
    op.execute("UPDATE settings SET is_public=TRUE WHERE setting_name='non_admin_registration_allowed'")
    op.alter_column('settings', 'is_public', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'is_public')
    # ### end Alembic commands ###
