""" "Object display properties"

Revision ID: b790f463f46e
Revises: 9e5329392687
Create Date: 2021-11-10 17:59:11.137404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b790f463f46e'
down_revision = '9e5329392687'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('composite_properties',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('display_mode', sa.Text()),
    sa.Column('numerate_chapters', sa.Boolean()),
    sa.UniqueConstraint('object_id'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], name=op.f('fk_composite_properties_object_id_objects'), ondelete='CASCADE')
    )

    op.execute("""
        INSERT INTO composite_properties (object_id, display_mode, numerate_chapters)
        SELECT DISTINCT object_id, 'basic', FALSE FROM composite
    """)
    op.alter_column('composite_properties', 'display_mode', nullable=False)
    op.alter_column('composite_properties', 'numerate_chapters', nullable=False)

    op.add_column('composite', sa.Column('show_description', sa.Text()))
    op.execute("UPDATE composite SET show_description='inherit'")
    op.alter_column('composite', 'show_description', nullable=False)

    op.add_column('composite', sa.Column('show_description_as_link', sa.Text()))
    op.execute("UPDATE composite SET show_description_as_link='inherit'")
    op.alter_column('composite', 'show_description_as_link', nullable=False)

    op.add_column('links', sa.Column('show_description_as_link', sa.Boolean()))
    op.execute('UPDATE links SET show_description_as_link=FALSE')
    op.alter_column('links', 'show_description_as_link', nullable=False)

    op.add_column('objects', sa.Column('show_description', sa.Boolean()))
    op.execute('UPDATE objects SET show_description=TRUE')
    op.alter_column('objects', 'show_description', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'show_description')
    op.drop_column('links', 'show_description_as_link')
    op.drop_column('composite', 'show_description_as_link')
    op.drop_column('composite', 'show_description')
    op.drop_table('composite_properties')
    # ### end Alembic commands ###
