""" "Searchables"

Revision ID: e66848bfd877
Revises: a6226d6df55f
Create Date: 2022-04-14 18:41:50.159023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e66848bfd877'
down_revision = 'a6226d6df55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchables',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('text_a', sa.Text(), nullable=True),
    sa.Column('text_b', sa.Text(), nullable=True),
    sa.Column('text_c', sa.Text(), nullable=True),
    sa.Column('searchable_tsv_russian', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', COALESCE(text_a, '')), 'A') || setweight(to_tsvector('russian', COALESCE(text_b, '')), 'B') || setweight(to_tsvector('russian', COALESCE(text_c, '')), 'C')", ), nullable=True),
    # sa.Column('searchable_tsv_english', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', COALESCE(text_a, '')), 'A') || setweight(to_tsvector('english', COALESCE(text_b, '')), 'B') || setweight(to_tsvector('english', COALESCE(text_c, '')), 'C')", ), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], name=op.f('fk_searchables_object_id_objects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('fk_searchables_tag_id_tags'), ondelete='CASCADE')
    )
    op.create_index('ix_searchable_russian', 'searchables', ['searchable_tsv_russian'], unique=False, postgresql_using='gin')
    # op.create_index('ix_searchable_english', 'searchables', ['searchable_tsv_english'], unique=False, postgresql_using='gin')


def downgrade():
    # op.drop_index('ix_searchable_english', table_name='searchables')
    op.drop_index('ix_searchable_russian', table_name='searchables')
    op.drop_table('searchables')
