""" "test 3"

Revision ID: e97b231c5966
Revises: 91928f159ec7
Create Date: 2022-05-29 15:22:25.985959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97b231c5966'
down_revision = '91928f159ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
